### ISSUE TITLE
InfluxDB auf anderen server

### ISSUE THREAD

**Issue by marco-mh** [zottelbeyer/QNAP-collectdinfluxdbgrafana#13]
Hallo, sorry ich spreche leider kein englisch.
Da ich bereits eine InfluxDB und eine Grafana auf einem Proxmox Server zu laufen habe, würde ich gerne diese weiter verwenden. welche Einstellungen muss ich ändern um die Daten an den Proxmox zu leiten. Danke

**Comment by zottelbeyer** [comment]
Moin. Im groben in etwa so:

docker-compose.yml anpassen um nur collectd zu deployen:

```
version: '3'

services:  
  collectd:
    container_name: qnap-collectd
    image: zottelbeyer/qnap-collectd:latest
    privileged: true
    network_mode: host
    volumes:
      - /:/rootfs/:ro
      - ./qnap-collectd/collectd.conf.d:/etc/collectd/collectd.conf.d/:ro    
    restart: always
```

collectd.config anpassen und den influxdb server eintragen:

https://github.com/zottelbeyer/QNAP-collectdinfluxdbgrafana/blob/master/qnap-collectd/collectd.conf.d/sample.conf#L18-L20

und dashboard importieren und anpassen:

https://github.com/zottelbeyer/QNAP-collectdinfluxdbgrafana/blob/master/grafana/QNAP-collectd-external.json
