### ISSUE TITLE
environment variable are taking effect

### ISSUE THREAD

**Issue by balajeek** [zottelbeyer/QNAP-collectdinfluxdbgrafana#17]
in docker-compose yml 
i made changes to environment variables by setting username and password, it does not work, it still accepts the username as "user" and password as "password" only.

I also put few other environment variables to disable_sanitize_html, anonymous login and so, and nothing seem to take effect.

what am I doing wrong?

**Comment by zottelbeyer** [comment]
Default variable contents, such as username and password are configured in .env:

 https://github.com/zottelbeyer/QNAP-collectdinfluxdbgrafana/blob/master/.env 

for further configuration read the grafana documentation:

https://grafana.com/docs/grafana/latest/setup-grafana/configure-grafana/#override-configuration-with-environment-variables

`GF_PANELS_DISABLE_SANITIZE_HTML: true`

in docker-compose.yml should work.

**Comment by balajeek** [comment]
Are you saying that i have to add the user/pass variable in my Os .env file?

But other environment variable i put does not seem to take effect either which is my issue:
here is the code part for grafana from my docker-compose file:
```

  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    user: "root"
    environment:
      - GF_SECURITY_ADMIN_USER= test  #${GF_SECURITY_ADMIN_USER} somehow this setting did not work, #default is "user"
      - GF_SECURITY_ADMIN_PASSWORD= test123  #${GF_SECURITY_ADMIN_PASSWORD} #default is "password"
      - GF_SECURITY_ALLOW_EMBEDDING= true
      - GF_PANELS_DISABLE_SANITIZE_HTML= true
      - GF_AUTH_DISABLE_LOGIN_FORM= true
      - GF_AUTH_ANONYMOUS_ENABLED= true
      - GF_AUTH_ANONYMOUS_ORG_NAME= Main Org
      - GF_AUTH_ANONYMOUS_ORG_ROLE= Editor
      - GF_USERS_ALLOW_SIGN_UP= false

```
