### ISSUE TITLE
Problem with http://192.168.1.47:3001/datasources/edit/1/

### ISSUE THREAD

**Issue by Peterpan62** [zottelbeyer/QNAP-collectdinfluxdbgrafana#19]
Hi,
I ran the installation but the problem was:
Error response from daemon: driver failed programming external connectivity on endpoint grafana (f387da3e1e214d2af84007c331d3771eedea6f06627d07d5da0074b5c934c4d5): listen tcp4 0.0.0.0:3000: bind: address already in use
I changed the docker-compose.yml
with graphana:
    container_name: grafana
    image: grafana/grafana:latest
    user: "root"
    environment:
      GF_SECURITY_ADMIN_USER: ${GF_SECURITY_ADMIN_USER}
      GF_SECURITY_ADMIN_PASSWORD: ${GF_SECURITY_ADMIN_PASSWORD}
    ports:
      - "3001:3001"

But the problem is that I can't see it
http://192.168.1.47:3001/datasources/edit/1/
everything else seems to work fine.
I have a qnap with container station installed

**Comment by Peterpan62** [comment]
http://192.168.1.47:8086/query?db=collectd&q=SHOW%20SERIES work fine

**Comment by zottelbeyer** [comment]
What you want is:

```
  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    user: "root"
    environment:
      GF_SECURITY_ADMIN_USER: ${GF_SECURITY_ADMIN_USER}
      GF_SECURITY_ADMIN_PASSWORD: ${GF_SECURITY_ADMIN_PASSWORD}
    ports:
      - "3001:3000"
    volumes:
      - ./grafana/datasource.yaml:/etc/grafana/provisioning/datasources/datasource.yaml
      - ./grafana/dashboard.yaml:/etc/grafana/provisioning/dashboards/dashboard.yaml
      - ./grafana/QNAP-collectd.json:/var/lib/grafana/dashboards/QNAP-collectd.json
      - ./grafana-data:/var/lib/grafana
    restart: always
```
